const faqs = [
  {
    q: 'Is this really me?',
    a: 'It is a simulation model trained on what you share — your style, values, and communication patterns.',
  },
  {
    q: 'Do both people need to opt in?',
    a: 'Yes. No opt-in, no simulation. Mutual consent is a hard requirement.',
  },
  {
    q: 'Is this a real person chatting?',
    a: 'No. You are seeing synthetic clone-to-clone dialogue generated by the simulation engine.',
  },
  {
    q: 'Can I delete my clone?',
    a: 'Yes. Delete, pause, or rebuild your clone at any time from your settings.',
  },
  {
    q: 'How accurate is the simulation?',
    a: 'It is directionally useful for chemistry and conflict patterns, not a guaranteed future.',
  },
];

export function FAQSection() {
  return (
    <section className="section-shell">
      <h2 className="mb-8 text-3xl font-semibold sm:text-4xl">FAQ</h2>
      <div className="space-y-3">
        {faqs.map((faq) => (
          <details className="glass group p-5" key={faq.q}>
            <summary className="cursor-pointer list-none text-base font-medium text-zinc-100">{faq.q}</summary>
            <p className="mt-3 text-sm text-zinc-300">{faq.a}</p>
          </details>
        ))}
      </div>
    </section>
  );
}
